image: continuumio/miniconda3

before_script:
  # creating and entering conda enviroment
  - conda env create -f environment.yml
  - source activate cobramod
  - conda info
  # This initiates pip and install the corresponding package
  - pip install . -v

stages:
  - build
  - linter
  - functions
  - example

test_docs:
  stage: build
  script:
    sphinx-build -b html docs/source/ docs/build/
  allow_failure: true
  only:
    - master
    - merge_requests

test_linters:
  stage: linter
  script:
    # Black is currently not recognizing .toml
    - black src/cobramod/ tests/ --line-length=79 --check
    - flake8 src/cobramod/ tests/ --config=.toml
    - mypy src/cobramod/ tests/ --config-file=.toml
  only:
    - master
    - merge_requests

test_logical:
  stage: functions
  script:
    - python3 -m unittest tests/test_creation.py -v
    - python3 -m unittest tests/test_extension.py -v
    - python3 -m unittest tests/test_graph.py -v
    - python3 -m unittest tests/test_mod_parser.py -v
    - python3 -m unittest tests/test_parsing.py -v
    - python3 -m unittest tests/test_pathway.py -v
    - python3 -m unittest tests/test_utils.py -v
  only:
    - master
    - merge_requests

test_models:
  stage: functions
  script:
    # Building model
    - python3 tests/extra/creating_test_model.py
    - python3 -m unittest tests/test_models.py -v
  only:
    - master
    - merge_requests

test_example:
  stage: example
  script:
    - python3 -m unittest tests/test_glucosinolate.py -v
  only:
    - master
    - merge_requests

