repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: no-commit-to-branch
        args: [-b master]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
        - id: ruff
        - id: ruff-format
          args: [--config=pyproject.toml, --check]
