version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-4.7"

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - escher
