version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
    nodejs: "latest"
  jobs:
      pre_create_environment:
        - npm install --global yarn
        - yarn install
        - yarn run vite build

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - escher
