[flake8]
extend-ignore = E203
max-line-length = 79
max-complexity = 18
select = B,C,E,F,W,T4,B9

[mypy]
python_version = 3.7
show_column_numbers = True
ignore_missing_imports = True
follow_imports = silent
