name: cobramod
channels:
- defaults
- bioconda
- conda-forge
- jasonb857
dependencies:
- black
- conda-forge::cobra
- bioconda::escher
- jasonb857::ipywidgets
- jupyter
- jupytext
- matplotlib
- mypy
- pynvim
- python
- ruff
- pre-commit
- pip:
  - Sphinx
  - sphinx-rtd-theme
  - sphinxcontrib-napoleon
  - doc8
  - nbsphinx
  - sphinx-autoapi
  - sphinxcontrib-bibtex
