name: cobramod-dev
channels:
- defaults
- bioconda
- conda-forge
dependencies:
- colorlog
- conda-forge::cobra
- jupyter
- jupytext
- matplotlib
- mypy
- python
- ruff
- pre-commit
- tqdm
- pyarrow
- pandoc
- conda-forge::webcolors
- conda-forge::openpyxl
- conda-forge::tox
- conda-forge::sphinx
- conda-forge::nbsphinx
- conda-forge::sphinx-autoapi
- conda-forge::jupyter_contrib_nbextensions
- pip:
  - escher-legacy
  - sphinx-rtd-theme
  - sphinxcontrib-napoleon
  - sphinxcontrib-bibtex
