name: cobramod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.4
  - pip=20.2.2
  - wheel=0.34.2=py37_0
  - virtualenv=20.0.34=py37_0
  - pre_commit=2.7.1=1
  - pandoc=2.12
  - pip:
    - appdirs==1.4.4
    - attrs==19.3.0
    - black==19.10b0
    - certifi==2020.6.20
    - click==7.1.2
    - cobra==0.18.1
    - depinfo==1.5.4
    - flake8==3.8.3
    - future==0.18.2
    - importlib-metadata==1.7.0
    - mccabe==0.6.1
    - mpmath==1.1.0
    - mypy==0.782
    - mypy-extensions==0.4.3
    - numpy==1.19.1
    - optlang==1.4.4
    - pandas==1.1.0
    - pathspec==0.8.0
    - pipdeptree==1.0.0
    - pycodestyle==2.6.0
    - pyflakes==2.2.0
    - python-dateutil==2.8.1
    - python-libsbml-experimental==5.18.1
    - regex==2020.7.14
    - requests==2.24.0
    - ruamel-yaml==0.16.10
    - ruamel-yaml-clib==0.2.0
    - swiglpk==4.65.1
    - sympy==1.6.1
    - toml==0.10.1
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.2
    - zipp==3.1.0
    - Sphinx==3.2.1
    - sphinx-rtd-theme==0.5.2
    - sphinxcontrib-napoleon==0.7
    - doc8==0.8.1
    - Escher==1.7.3
    - openpyxl==3.0.7
    - nbsphinx==0.8.4
    - webcolors==1.11.1
    - sphinx-autoapi==1.8.1

