name: cobramod
channels:
- defaults
- bioconda
- conda-forge
- jasonb857
dependencies:
- black
- conda-forge::cobra
- bioconda::escher
- jasonb857::ipywidgets
- jasonb857::jinja2
- jupyter
- jupytext
- matplotlib
- mypy
- pynvim
- python
- ruff
- pre-commit
- conda-forge::sphinx
- conda-forge::nbsphinx
- conda-forge::sphinx-autoapi
- pip:
  - sphinx-rtd-theme
  - sphinxcontrib-napoleon
  - doc8
  - sphinxcontrib-bibtex
  - openpyxl
