name: cobramod-dev
channels:
- defaults
- bioconda
- conda-forge
- jasonb857
dependencies:
- colorlog
- conda-forge::cobra
- bioconda::escher
- jasonb857::ipywidgets
- jasonb857::jinja2
- jupyter
- jupytext
- matplotlib
- mypy
- python
- ruff
- pre-commit
- tqdm
- pyarrow
- conda-forge::webcolors
- conda-forge::openpyxl
- conda-forge::tox
- conda-forge::sphinx
- conda-forge::nbsphinx
- conda-forge::sphinx-autoapi==2.0
- conda-forge::jupyter_contrib_nbextensions
- pip:
  - sphinx-rtd-theme
  - sphinxcontrib-napoleon
  - sphinxcontrib-bibtex
