name: cobramod-dev
channels:
- defaults
- bioconda
- conda-forge
dependencies:
- colorlog
- conda-forge::cobra
- jupyter
- jupytext
- matplotlib
- mypy
- python
- ruff
- pre-commit
- tqdm
- pyarrow
- docutils
- pandoc
- conda-forge::webcolors
- conda-forge::openpyxl
- conda-forge::tox
- conda-forge::sphinx
- conda-forge::nbsphinx
- conda-forge::jupyter_contrib_nbextensions
- pip:
  - escher-legacy
  - sphinx-rtd-theme
  - sphinxcontrib-napoleon
  - sphinxcontrib-bibtex
  - anywidget[dev]
  - sphinx-autoapi==3.1.0b0
  - jupyter-sphinx
