name: Cobramod under a conda enviroment
on:
  push:
    branches:
      - master
      - internal/transition-github
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  test:
    runs-on: ubuntu-latest
    name: test to check stages
    container: continuumio/miniconda3
    steps:
      - name: create enviroment
        run: |
          pwd
          ls -la
          conda env create -f enviroment.yml
          conda activate cobramod
          conda info
          pip install . -v
  

