name: Build of cobramod under a conda environment
on:
  push:
    branches:
      - master
      - internal/transition-github
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  linter:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    name: package-linter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Enviroment-build
        uses: ./.github/conda-build
      - name: linter
        run: |
          source activate cobramod
          black src/cobramod/ tests/ --line-length=79 --check
          flake8 src/cobramod/ tests/ --config=.toml
          mypy src/cobramod/ tests/ --config-file=.toml
  function:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    name: package-test-methods
    needs: [linter]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Enviroment-build
        uses: ./.github/conda-build
      - name: Unit-test
        run: |
          source activate cobramod
          python3 -m unittest tests/test_creation.py -v
          python3 -m unittest tests/test_extension.py -v
          python3 -m unittest tests/test_graph.py -v
          python3 -m unittest tests/test_mod_parser.py -v
          python3 -m unittest tests/test_parsing.py -v
          python3 -m unittest tests/test_pathway.py -v
          python3 -m unittest tests/test_utils.py -v
  models:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    name: package-test-methods
    needs: [linter]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Enviroment-build
        uses: ./.github/conda-build
      - name: Unit-test
        run: |
          source activate cobramod
          python3 tests/extra/creating_test_model.py
          python3 -m unittest tests/test_models.py -v
  example:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    name: package-test-methods
    needs: [models]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Enviroment-build
        uses: ./.github/conda-build
      - name: methods
        run: |
          source activate cobramod
          python3 -m unittest tests/test_glucosinolate.py -v
