name: Cobramod under a conda enviroment
on:
  push:
    branches:
      - master
      - internal/transition-github
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  test:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    name: Checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: enviroment-build
        uses: ./.github/conda-build
      - name: linter
        run: | 
          black src/cobramod/ tests/ --line-length=79 --check
          flake8 src/cobramod/ tests/ --config=.toml
          mypy src/cobramod/ tests/ --config-file=.toml

